/**
 * @fileoverview gRPC-Web generated client stub for web
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: weather_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.web = require('./weather_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.web.WeatherServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.web.WeatherServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.web.WeatherRequest,
 *   !proto.web.WeatherResponse>}
 */
const methodDescriptor_WeatherService_GetWeather = new grpc.web.MethodDescriptor(
  '/web.WeatherService/GetWeather',
  grpc.web.MethodType.UNARY,
  proto.web.WeatherRequest,
  proto.web.WeatherResponse,
  /**
   * @param {!proto.web.WeatherRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.web.WeatherResponse.deserializeBinary
);


/**
 * @param {!proto.web.WeatherRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.web.WeatherResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.web.WeatherResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.web.WeatherServiceClient.prototype.getWeather =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/web.WeatherService/GetWeather',
      request,
      metadata || {},
      methodDescriptor_WeatherService_GetWeather,
      callback);
};


/**
 * @param {!proto.web.WeatherRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.web.WeatherResponse>}
 *     Promise that resolves to the response
 */
proto.web.WeatherServicePromiseClient.prototype.getWeather =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/web.WeatherService/GetWeather',
      request,
      metadata || {},
      methodDescriptor_WeatherService_GetWeather);
};


module.exports = proto.web;

